# Generated by Django 6.0.6 on 2026-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_company_alter_user_role'),
        ('company', '0002_alter_company_postal_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_role_per_company',
        ),
        migrations.AddField(
            model_name='role',
            name='role_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'role_name'), name='unique_role_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'role_code'), name='unique_role_code_per_company'),
        ),
    ]
