# Generated by Django 6.0.6 on 2026-06-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_role_unique_role_per_company_role_role_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_code',
            field=models.CharField(max_length=30),
        ),
    ]
