# Generated by Django 6.0.6 on 2026-06-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_permission_rolepermission_role_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['permission_code']},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role', 'permission']},
        ),
    ]
