# Generated by Django 6.0.6 on 2026-08-02 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('LEAVE_REQUEST', 'Leave Request'), ('LEAVE_APPROVAL', 'Leave Approval'), ('LEAVE_REJECTION', 'Leave Rejection'), ('PAYROLL_PROCESSED', 'Payroll Processed'), ('PAYMENT_PENDING', 'Payment Pending'), ('ASSET_ASSIGNED', 'Asset Assigned'), ('MAINTENANCE_DUE', 'Maintenance Due'), ('ATTENDANCE_EXCEPTION', 'Attendance Exception')], default='SYSTEM', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='company.company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['company', 'recipient'], name='notificatio_company_73f089_idx')],
            },
        ),
    ]
