# Generated by Django 6.0.6 on 2026-07-02 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('employees', 'Employees'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('inventory', 'Inventory'), ('payments', 'Payments')], db_index=True, max_length=20)),
                ('export_format', models.CharField(choices=[('excel', 'Excel (.xlsx)'), ('csv', 'CSV (.csv)'), ('pdf', 'PDF (.pdf)')], default='excel', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('filters_applied', models.JSONField(blank=True, default=dict, help_text='Query filters used when generating this export.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='company.company')),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Log',
                'verbose_name_plural': 'Export Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='data_exchan_company_d337da_idx'), models.Index(fields=['module'], name='data_exchan_module_d3a14e_idx'), models.Index(fields=['created_at'], name='data_exchan_created_c84170_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('employees', 'Employees'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('inventory', 'Inventory'), ('payments', 'Payments')], db_index=True, help_text='Which ERP module this import targets.', max_length=20)),
                ('original_filename', models.CharField(help_text='Original filename uploaded by the user.', max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(default=0, help_text='Size of the uploaded file in bytes.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preview', 'Preview'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0, help_text='Total data rows in the uploaded file.')),
                ('valid_rows', models.PositiveIntegerField(default=0, help_text='Rows that passed all validation checks.')),
                ('failed_rows', models.PositiveIntegerField(default=0, help_text='Rows that failed one or more validation checks.')),
                ('imported_rows', models.PositiveIntegerField(default=0, help_text='Rows actually written to the database.')),
                ('errors', models.JSONField(blank=True, default=list, help_text='Structured list of row-level validation errors. Format: [{row, column, message}, ...]')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='Non-blocking warnings found during validation. Import can proceed despite warnings.')),
                ('preview_data', models.JSONField(blank=True, default=list, help_text='Validated and cleaned rows stored between preview and confirm steps. Cleared after import.')),
                ('error_summary', models.TextField(blank=True, default='', help_text='Top-level error message if the whole import failed.')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the import was initiated.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the import finished (success or failure).', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Total time taken to complete the import.', null=True)),
                ('company', models.ForeignKey(help_text='Company that performed the import.', on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='company.company')),
                ('imported_by', models.ForeignKey(help_text='User who initiated the import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company'], name='data_exchan_company_aa3646_idx'), models.Index(fields=['module'], name='data_exchan_module_960f07_idx'), models.Index(fields=['status'], name='data_exchan_status_64efe3_idx'), models.Index(fields=['started_at'], name='data_exchan_started_bee05a_idx')],
            },
        ),
    ]
