# Generated by Django 6.0.6 on 2026-06-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='company.company')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['company', 'name'],
                'indexes': [models.Index(fields=['company'], name='inventory_a_company_4d9f11_idx'), models.Index(fields=['is_active'], name='inventory_a_is_acti_194283_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_asset_category_per_company')],
            },
        ),
    ]
