# Generated by Django 6.0.6 on 2026-06-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('inventory', '0001_asset_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about this vendor. e.g. payment terms, reliability, warranty support quality.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='company.company')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['company', 'name'],
                'indexes': [models.Index(fields=['company'], name='inventory_v_company_a443b1_idx'), models.Index(fields=['is_active'], name='inventory_v_is_acti_618271_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_vendor_name_per_company')],
            },
        ),
    ]
