# Generated by Django 6.0.6 on 2026-06-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('inventory', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(help_text='Internal company asset tag. e.g. LAP-0001, CHR-0045', max_length=50)),
                ('name', models.CharField(help_text='e.g. Dell Latitude 5420', max_length=150)),
                ('serial_number', models.CharField(blank=True, default='', help_text='Manufacturer serial number, if applicable.', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Maintenance', 'Maintenance'), ('Lost', 'Lost'), ('Damaged', 'Damaged'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='New', max_length=20)),
                ('location', models.CharField(blank=True, default='', help_text='Physical location when not assigned. e.g. IT Store Room, Floor 3 Storage', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Cannot delete a category that has assets assigned to it.', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.assetcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='company.company')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor this asset was purchased from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.vendor')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['company', 'category', 'asset_tag'],
                'indexes': [models.Index(fields=['company'], name='inventory_a_company_e0ec09_idx'), models.Index(fields=['category'], name='inventory_a_categor_4ca7a3_idx'), models.Index(fields=['vendor'], name='inventory_a_vendor__85e309_idx'), models.Index(fields=['status'], name='inventory_a_status_69dd7e_idx'), models.Index(fields=['asset_tag'], name='inventory_a_asset_t_f5ad3d_idx'), models.Index(fields=['serial_number'], name='inventory_a_serial__4865f1_idx'), models.Index(fields=['is_active'], name='inventory_a_is_acti_81dae2_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'asset_tag'), name='unique_asset_tag_per_company')],
            },
        ),
    ]
