# Generated by Django 6.0.6 on 2026-06-30 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('employees', '0010_employeeshiftassignment_unique_active_shift_per_employee'),
        ('inventory', '0003_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag_snapshot', models.CharField(help_text='Snapshot of the asset tag at assignment time.', max_length=50)),
                ('employee_name_snapshot', models.CharField(help_text="Snapshot of the employee's full name at assignment time.", max_length=255)),
                ('assigned_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, help_text='Leave blank while the employee currently holds this asset.', null=True)),
                ('assigned_condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', help_text='Condition of the asset when assigned.', max_length=20)),
                ('returned_condition', models.CharField(blank=True, choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], help_text='Condition of the asset when returned.', max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Cannot delete an asset that has assignment history.', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.asset')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='company.company')),
                ('employee', models.ForeignKey(help_text='Cannot delete an employee that has asset assignment history.', on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='employees.employee')),
                ('received_by', models.ForeignKey(blank=True, help_text='Who processed the asset return.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_returns_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'verbose_name_plural': 'Asset Assignments',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['company'], name='inventory_a_company_bfe355_idx'), models.Index(fields=['asset'], name='inventory_a_asset_i_225fd7_idx'), models.Index(fields=['employee'], name='inventory_a_employe_6f8d0b_idx'), models.Index(fields=['assigned_date'], name='inventory_a_assigne_881d19_idx'), models.Index(fields=['returned_date'], name='inventory_a_returne_07e326_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_date__isnull', True)), fields=('asset',), name='unique_active_assignment_per_asset'), models.CheckConstraint(condition=models.Q(('returned_date__isnull', True), ('returned_date__gte', models.F('assigned_date')), _connector='OR'), name='returned_date_after_assigned_date')],
            },
        ),
    ]
