# Generated by Django 6.0.6 on 2026-06-30 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('inventory', '0004_asset_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag_snapshot', models.CharField(help_text='Snapshot of the asset tag at maintenance creation time.', max_length=50)),
                ('maintenance_type', models.CharField(choices=[('Repair', 'Repair'), ('Cleaning', 'Cleaning'), ('Upgrade', 'Upgrade'), ('Inspection', 'Inspection'), ('Preventive', 'Preventive Maintenance'), ('Other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('description', models.TextField(help_text='What needs to be done / was done.')),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outcome_notes', models.TextField(blank=True, default='', help_text='Result of the maintenance. e.g. Battery replaced successfully, Beyond repair, recommend retirement.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Cannot delete an asset that has maintenance history.', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='inventory.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_maintenances', to='company.company')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reports_created', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor/service provider who performed the work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to='inventory.vendor')),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenance Records',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['company'], name='inventory_a_company_954cd6_idx'), models.Index(fields=['asset'], name='inventory_a_asset_i_ed61da_idx'), models.Index(fields=['vendor'], name='inventory_a_vendor__8fff4e_idx'), models.Index(fields=['status'], name='inventory_a_status_f12e4f_idx'), models.Index(fields=['maintenance_type'], name='inventory_a_mainten_4e6caa_idx'), models.Index(fields=['scheduled_date'], name='inventory_a_schedul_869836_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('completed_date__isnull', True), ('completed_date__gte', models.F('scheduled_date')), _connector='OR'), name='completed_date_after_scheduled_date')],
            },
        ),
    ]
