# Generated by Django 6.0.6 on 2026-06-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('National', 'National Holiday'), ('Festival', 'Festival'), ('Company', 'Company Holiday'), ('Optional', 'Optional Holiday'), ('Other', 'Other')], default='National', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Employees may choose to take this holiday.')),
                ('is_recurring', models.BooleanField(default=True, help_text='Whether this holiday repeats every year.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='company.company')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ('date', 'name'),
                'indexes': [models.Index(fields=['company'], name='attendance__company_e63dd7_idx'), models.Index(fields=['date'], name='attendance__date_54d65e_idx'), models.Index(fields=['is_active'], name='attendance__is_acti_eb91f3_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='unique_holiday_per_company_per_date')],
            },
        ),
    ]
