# Generated by Django 6.0.6 on 2026-06-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='type',
            new_name='holiday_type',
        ),
    ]
