# Generated by Django 6.0.6 on 2026-06-26 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_type_holiday_holiday_type'),
        ('employees', '0009_employeeshiftassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('working_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_exit_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('Leave', 'Leave'), ('Holiday', 'Holiday'), ('Week Off', 'Week Off'), ('Work From Home', 'Work From Home')], default='Absent', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='employees.shift')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ('-date', 'employee'),
                'indexes': [models.Index(fields=['employee'], name='attendance__employe_c89dc0_idx'), models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx'), models.Index(fields=['is_active'], name='attendance__is_acti_a7c189_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_per_employee_per_day')],
            },
        ),
    ]
