# Generated by Django 6.0.6 on 2026-06-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='scheduled_grace_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
