# Generated by Django 6.0.6 on 2026-06-26 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_scheduled_grace_minutes'),
        ('employees', '0009_employeeshiftassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approval_reason',
            field=models.TextField(blank=True, help_text='Reason for approval or rejection.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', help_text='Approval status of this attendance record.', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this attendance record was approved.', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this attendance record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_modified',
            field=models.BooleanField(default=False, help_text='True if this record was modified after creation.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Web', 'Web'), ('Mobile', 'Mobile'), ('Biometric', 'Biometric'), ('API', 'API')], default='Web', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_name_snapshot',
            field=models.CharField(blank=True, help_text='Shift name at the time attendance was recorded.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_source'], name='attendance__attenda_ab3f39_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['approval_status'], name='attendance__approva_ff8789_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_modified'], name='attendance__attenda_7a2cfe_idx'),
        ),
    ]
