# Generated by Django 6.0.6 on 2026-06-30 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('employees', '0010_employeeshiftassignment_unique_active_shift_per_employee'),
        ('payroll', '0007_payslip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(help_text='Internal unique payment reference. e.g. PAY-2026-000001', max_length=30, unique=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date the payment was actually processed/sent. Left blank while Pending.', null=True)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount authorized for this payment. Snapshot — independent of later payslip recalculations.', max_digits=12)),
                ('bank_reference_number', models.CharField(blank=True, default='', help_text='Bank-issued reference number for this transfer, if applicable.', max_length=100)),
                ('transaction_id', models.CharField(blank=True, default='', help_text='Payment gateway / processor transaction ID (e.g. Razorpay payout ID).', max_length=100)),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Populated when status = Failed. Explains why the payment did not go through.')),
                ('remarks', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='company.company')),
                ('employee', models.ForeignKey(help_text='Cannot delete an employee that has payment history.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='employees.employee')),
                ('payslip', models.ForeignKey(help_text='Cannot delete a payslip that has a payment record.', on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payroll.payslip')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who last moved this payment through the workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='payments_pa_company_89c7b4_idx'), models.Index(fields=['employee'], name='payments_pa_employe_76746b_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['payment_method'], name='payments_pa_payment_5c92d7_idx'), models.Index(fields=['payment_number'], name='payments_pa_payment_a0847d_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive')],
            },
        ),
    ]
