# Generated by Django 6.0.6 on 2026-06-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Basic Salary, HRA, PF', max_length=150)),
                ('code', models.CharField(help_text='e.g. BASIC, HRA, PF', max_length=20)),
                ('component_type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], help_text='Earning or Deduction', max_length=20)),
                ('calculation_type', models.CharField(choices=[('Fixed', 'Fixed Amount'), ('Percentage', 'Percentage of Basic')], default='Fixed', help_text='Fixed: a flat amount. Percentage: % of basic salary.', max_length=20)),
                ('default_value', models.DecimalField(decimal_places=4, default=0, help_text='Default amount or percentage. Can be overridden per employee.', max_digits=10)),
                ('is_taxable', models.BooleanField(default=False, help_text='If True, this component is included in taxable income.')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If True, this component is always included in every payslip and cannot be removed per employee.')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='company.company')),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
                'ordering': ['company', 'component_type', 'name'],
                'indexes': [models.Index(fields=['company'], name='payroll_sal_company_d157f4_idx'), models.Index(fields=['component_type'], name='payroll_sal_compone_c97d5c_idx'), models.Index(fields=['is_active'], name='payroll_sal_is_acti_9731dc_idx'), models.Index(fields=['is_mandatory'], name='payroll_sal_is_mand_b618cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_component_name_per_company'), models.UniqueConstraint(fields=('company', 'code'), name='unique_component_code_per_company')],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank if the structure is currently active with no end date.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='company.company')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['company', 'name'],
                'indexes': [models.Index(fields=['company'], name='payroll_sal_company_f1f9c9_idx'), models.Index(fields=['is_active'], name='payroll_sal_is_acti_deb13f_idx'), models.Index(fields=['effective_from'], name='payroll_sal_effecti_cb7e40_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_salary_structure_per_company')],
            },
        ),
    ]
