# Generated by Django 6.0.6 on 2026-06-28 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_calculation_type', models.CharField(blank=True, choices=[('Fixed', 'Fixed Amount'), ('Percentage', 'Percentage of Basic')], help_text="If set, overrides the component's default calculation type for this structure only.", max_length=20, null=True)),
                ('override_value', models.DecimalField(blank=True, decimal_places=4, help_text="If set, overrides the component's default value for this structure only.", max_digits=10, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Controls the order in which this component appears on the payslip.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(help_text='Cannot delete a component that is assigned to a structure.', on_delete=django.db.models.deletion.PROTECT, related_name='structure_components', to='payroll.salarycomponent')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_components', to='payroll.salarystructure')),
            ],
            options={
                'verbose_name': 'Salary Structure Component',
                'verbose_name_plural': 'Salary Structure Components',
                'ordering': ['structure', 'display_order', 'component'],
                'indexes': [models.Index(fields=['structure'], name='payroll_sal_structu_7ca569_idx'), models.Index(fields=['component'], name='payroll_sal_compone_e804d8_idx'), models.Index(fields=['is_active'], name='payroll_sal_is_acti_e07323_idx')],
                'constraints': [models.UniqueConstraint(fields=('structure', 'component'), name='unique_component_per_structure')],
            },
        ),
    ]
