# Generated by Django 6.0.6 on 2026-06-28 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('employees', '0010_employeeshiftassignment_unique_active_shift_per_employee'),
        ('payroll', '0002_salarystructurecomponent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text="The employee's basic salary. Percentage-based components are calculated from this value.", max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Total earnings before deductions. Calculated automatically during payroll generation.', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Gross salary minus all deductions. Calculated automatically during payroll generation.', max_digits=12)),
                ('effective_from', models.DateField(help_text='The date from which this salary record is effective.')),
                ('effective_to', models.DateField(blank=True, help_text='The date until which this salary record is effective. Leave blank for the current record.', null=True)),
                ('remarks', models.TextField(blank=True, default='', help_text='Reason for this salary record. e.g. Joining, Annual Increment, Promotion, Revision.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active salary record should exist per employee at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salaries', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employee')),
                ('structure', models.ForeignKey(help_text='The salary structure assigned to this employee.', on_delete=django.db.models.deletion.PROTECT, related_name='employee_salaries', to='payroll.salarystructure')),
            ],
            options={
                'verbose_name': 'Employee Salary',
                'verbose_name_plural': 'Employee Salaries',
                'ordering': ['employee', '-effective_from'],
                'indexes': [models.Index(fields=['company'], name='payroll_emp_company_c53d98_idx'), models.Index(fields=['employee'], name='payroll_emp_employe_11dc88_idx'), models.Index(fields=['structure'], name='payroll_emp_structu_4f2d4b_idx'), models.Index(fields=['effective_from'], name='payroll_emp_effecti_75a0d4_idx'), models.Index(fields=['is_active'], name='payroll_emp_is_acti_572ea2_idx')],
            },
        ),
    ]
