# Generated by Django 6.0.6 on 2026-06-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('payroll', '0003_employeesalary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='net_salary',
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month number (1-12).')),
                ('year', models.PositiveSmallIntegerField(help_text='Four-digit year.')),
                ('start_date', models.DateField(help_text='First day of the payroll period.')),
                ('end_date', models.DateField(help_text='Last day of the payroll period.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('total_working_days', models.PositiveSmallIntegerField(default=0, help_text='Total working days in this cycle. Used to calculate per-day salary.')),
                ('remarks', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_payroll_cycles', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_cycles', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Cycle',
                'verbose_name_plural': 'Payroll Cycles',
                'ordering': ['company', '-year', '-month'],
                'indexes': [models.Index(fields=['company'], name='payroll_pay_company_43cce0_idx'), models.Index(fields=['status'], name='payroll_pay_status_3822b4_idx'), models.Index(fields=['year', 'month'], name='payroll_pay_year_8994ac_idx'), models.Index(fields=['start_date'], name='payroll_pay_start_d_f9ba73_idx'), models.Index(fields=['end_date'], name='payroll_pay_end_dat_74841c_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'month', 'year'), name='unique_payroll_cycle_per_month_year')],
            },
        ),
    ]
