# Generated by Django 6.0.6 on 2026-06-28 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('payroll', '0004_remove_employeesalary_gross_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveSmallIntegerField(default=1, help_text='Run number within the cycle. First run is 1, correction is 2, etc.')),
                ('description', models.TextField(blank=True, default='', help_text='e.g. Initial Run, Correction Run, Bonus Run.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Approved', 'Approved'), ('Finalized', 'Finalized'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('total_employees', models.PositiveIntegerField(default=0, help_text='Number of employees in this run.')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all gross salaries.', max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all deductions.', max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all net salaries.', max_digits=14)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(help_text='The payroll cycle this run belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='payroll.payrollcycle')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['company', '-created_at'],
                'indexes': [models.Index(fields=['company'], name='payroll_pay_company_593b3c_idx'), models.Index(fields=['cycle'], name='payroll_pay_cycle_i_4c0e2a_idx'), models.Index(fields=['status'], name='payroll_pay_status_5e02ca_idx'), models.Index(fields=['created_at'], name='payroll_pay_created_28957c_idx')],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'run_number'), name='unique_run_number_per_cycle')],
            },
        ),
    ]
