# Generated by Django 6.0.6 on 2026-06-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('employees', '0010_employeeshiftassignment_unique_active_shift_per_employee'),
        ('payroll', '0005_payrollrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(help_text='Snapshot of component name at generation time.', max_length=150)),
                ('component_type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], help_text='Snapshot of component type at generation time.', max_length=20)),
                ('calculation_type', models.CharField(choices=[('Fixed', 'Fixed Amount'), ('Percentage', 'Percentage of Basic')], help_text='Snapshot of calculation type at generation time.', max_length=20)),
                ('is_taxable', models.BooleanField(default=False, help_text='Snapshot of taxable status at generation time.')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, help_text='The basic salary used as base for percentage calculations.', max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, default=0, help_text='The rate or fixed amount used for this component.', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='The final calculated amount for this component.', max_digits=12)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Controls the order in which this item appears on the payslip.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='company.company')),
                ('component', models.ForeignKey(help_text='The salary component this item represents.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='payroll.salarycomponent')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'Payroll Item',
                'verbose_name_plural': 'Payroll Items',
                'ordering': ['employee', 'display_order', 'component_type'],
                'indexes': [models.Index(fields=['company'], name='payroll_pay_company_f1b20f_idx'), models.Index(fields=['payroll_run'], name='payroll_pay_payroll_b3253e_idx'), models.Index(fields=['employee'], name='payroll_pay_employe_d7c3d5_idx'), models.Index(fields=['component'], name='payroll_pay_compone_25da56_idx'), models.Index(fields=['component_type'], name='payroll_pay_compone_96d3ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('payroll_run', 'employee', 'component'), name='unique_component_per_employee_per_run')],
            },
        ),
    ]
