# Generated by Django 6.0.6 on 2026-06-28 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('employees', '0010_employeeshiftassignment_unique_active_shift_per_employee'),
        ('payroll', '0006_payroll_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text="Snapshot of the employee's basic salary.", max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Total earnings before deductions.', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, help_text='Total deductions applied.', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Final payable salary.', max_digits=12)),
                ('period_start', models.DateField(help_text='Payroll period start date.')),
                ('period_end', models.DateField(help_text='Payroll period end date.')),
                ('working_days', models.PositiveSmallIntegerField(default=0, help_text='Total payable working days.')),
                ('present_days', models.DecimalField(decimal_places=1, default=0, help_text='Employee present days.', max_digits=5)),
                ('paid_leave_days', models.DecimalField(decimal_places=1, default=0, help_text='Approved paid leave days.', max_digits=5)),
                ('loss_of_pay_days', models.DecimalField(decimal_places=1, default=0, help_text='Leave without pay days.', max_digits=5)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Generated', 'Generated'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('employee_salary', models.ForeignKey(help_text='Salary record used to generate this payslip.', on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.employeesalary')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_payslips', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['employee', '-created_at'],
                'indexes': [models.Index(fields=['company'], name='payroll_pay_company_1e855a_idx'), models.Index(fields=['payroll_run'], name='payroll_pay_payroll_de605b_idx'), models.Index(fields=['employee'], name='payroll_pay_employe_16c3a9_idx'), models.Index(fields=['status'], name='payroll_pay_status_409e9f_idx')],
                'constraints': [models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_payslip_per_employee_per_run')],
            },
        ),
    ]
