# Generated by Django 6.0.6 on 2026-06-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['company', 'department_name'],
                'indexes': [models.Index(fields=['company'], name='employees_d_company_81f4a6_idx'), models.Index(fields=['department_code'], name='employees_d_departm_2c5b76_idx'), models.Index(fields=['is_active'], name='employees_d_is_acti_97e269_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'department_name'), name='unique_department_name_per_company'), models.UniqueConstraint(fields=('company', 'department_code'), name='unique_department_code_per_company')],
            },
        ),
    ]
