# Generated by Django 6.0.6 on 2026-06-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=100)),
                ('designation_code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='company.company')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['company', 'designation_name'],
                'indexes': [models.Index(fields=['company'], name='employees_d_company_eec5cf_idx'), models.Index(fields=['designation_code'], name='employees_d_designa_94ea31_idx'), models.Index(fields=['is_active'], name='employees_d_is_acti_68bd43_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'designation_name'), name='unique_designation_name_per_company'), models.UniqueConstraint(fields=('company', 'designation_code'), name='unique_designation_code_per_company')],
            },
        ),
    ]
