# Generated by Django 6.0.6 on 2026-06-26 05:42

import django.core.validators
import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('employees', '0002_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, editable=False, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('profile_photo', models.ImageField(blank=True, upload_to='employees/photos/', validators=[employees.models.validate_profile_photo])),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Up to 15 digits. Optionally start with +.', regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Up to 15 digits. Optionally start with +.', regex='^\\+?1?\\d{9,15}$')])),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=15)),
                ('joining_date', models.DateField()),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('employee_status', models.CharField(choices=[('Active', 'Active'), ('Probation', 'Probation'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], default='Probation', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.designation')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['company', 'first_name', 'last_name'],
                'indexes': [models.Index(fields=['company'], name='employees_e_company_4fecd2_idx'), models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'), models.Index(fields=['department'], name='employees_e_departm_99b42d_idx'), models.Index(fields=['designation'], name='employees_e_designa_607b98_idx'), models.Index(fields=['employee_status'], name='employees_e_employe_294a4c_idx'), models.Index(fields=['is_active'], name='employees_e_is_acti_ff761b_idx'), models.Index(fields=['joining_date'], name='employees_e_joining_69a338_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee_id'), name='unique_employee_id_per_company'), models.UniqueConstraint(fields=('company', 'email'), name='unique_employee_email_per_company')],
            },
        ),
    ]
