# Generated by Django 6.0.6 on 2026-06-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('Current', 'Current'), ('Permanent', 'Permanent')], max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Address',
                'verbose_name_plural': 'Employee Addresses',
                'ordering': ['employee', 'address_type'],
                'indexes': [models.Index(fields=['employee'], name='employees_e_employe_60b298_idx'), models.Index(fields=['address_type'], name='employees_e_address_447a05_idx'), models.Index(fields=['is_active'], name='employees_e_is_acti_823fa1_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'address_type'), name='unique_address_type_per_employee')],
            },
        ),
    ]
