# Generated by Django 6.0.6 on 2026-06-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Guardian', 'Guardian'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['employee', '-is_primary', 'contact_name'],
                'indexes': [models.Index(fields=['employee'], name='employees_e_employe_d3fdfd_idx'), models.Index(fields=['relationship'], name='employees_e_relatio_1f3cb5_idx'), models.Index(fields=['phone'], name='employees_e_phone_74eeaf_idx'), models.Index(fields=['is_primary'], name='employees_e_is_prim_44b452_idx'), models.Index(fields=['is_active'], name='employees_e_is_acti_23da2a_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'phone'), name='unique_emergency_phone_per_employee')],
            },
        ),
    ]
