# Generated by Django 6.0.6 on 2026-06-26 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('branch_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Salary', 'Salary')], max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Bank Detail',
                'verbose_name_plural': 'Employee Bank Details',
                'ordering': ['employee', '-is_primary', 'bank_name'],
                'indexes': [models.Index(fields=['employee'], name='employees_e_employe_4926ce_idx'), models.Index(fields=['account_number'], name='employees_e_account_741c49_idx'), models.Index(fields=['ifsc_code'], name='employees_e_ifsc_co_ef8a71_idx'), models.Index(fields=['is_primary'], name='employees_e_is_prim_c2db70_idx'), models.Index(fields=['is_active'], name='employees_e_is_acti_91a7fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'account_number'), name='unique_bank_account_per_employee')],
            },
        ),
    ]
