# Generated by Django 6.0.6 on 2026-06-26 12:39

import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeebankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Aadhaar', 'Aadhaar'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Driving License', 'Driving License'), ('Resume', 'Resume'), ('Offer Letter', 'Offer Letter'), ('Experience Letter', 'Experience Letter'), ('Certificate', 'Certificate'), ('Other', 'Other')], max_length=30)),
                ('document_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to=employees.models.employee_document_upload_path)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['employee', 'document_type', 'document_name'],
                'indexes': [models.Index(fields=['employee'], name='employees_e_employe_8fba9b_idx'), models.Index(fields=['document_type'], name='employees_e_documen_3808ed_idx'), models.Index(fields=['is_verified'], name='employees_e_is_veri_ee34ff_idx'), models.Index(fields=['is_active'], name='employees_e_is_acti_c55f6a_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'document_type', 'document_name'), name='unique_document_per_employee')],
            },
        ),
    ]
