# Generated by Django 6.0.6 on 2026-06-26 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_postal_code'),
        ('employees', '0007_employeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
                ('shift_code', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.PositiveIntegerField(default=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='company.company')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['company', 'shift_name'],
                'indexes': [models.Index(fields=['company'], name='employees_s_company_ceb1d3_idx'), models.Index(fields=['shift_code'], name='employees_s_shift_c_43fd8d_idx'), models.Index(fields=['is_default'], name='employees_s_is_defa_c2ea74_idx'), models.Index(fields=['is_active'], name='employees_s_is_acti_9369ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'shift_name'), name='unique_shift_name_per_company'), models.UniqueConstraint(fields=('company', 'shift_code'), name='unique_shift_code_per_company')],
            },
        ),
    ]
