# Generated by Django 6.0.6 on 2026-06-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='employees.shift')),
            ],
            options={
                'verbose_name': 'Employee Shift Assignment',
                'verbose_name_plural': 'Employee Shift Assignments',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['employee'], name='employees_e_employe_fe0ea3_idx'), models.Index(fields=['shift'], name='employees_e_shift_i_3d7593_idx'), models.Index(fields=['effective_from'], name='employees_e_effecti_d35ae8_idx'), models.Index(fields=['is_active'], name='employees_e_is_acti_bb2a14_idx')],
            },
        ),
    ]
