# Generated by Django 6.0.6 on 2026-06-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeeshiftassignment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeeshiftassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee',), name='unique_active_shift_per_employee'),
        ),
    ]
